/*
 * config.h
 *
 *  Created on: Dec 12, 2022
 *      Author: janoko
 */

#ifndef QUECTEL_EC25_RTOS_EXAMPLES_SIMPLE_MODEM_CONFIG_H_
#define QUECTEL_EC25_RTOS_EXAMPLES_SIMPLE_MODEM_CONFIG_H_

#define QTEL_EN_FEATURE_SOCKET 1
#define QTEL_EN_FEATURE_NTP    1
#define QTEL_EN_FEATURE_GPS    1

#ifndef UART_MODEM_HANDLER
#define UART_MODEM_HANDLER    huart3
#endif

#endif /* QUECTEL_EC25_RTOS_EXAMPLES_SIMPLE_MODEM_CONFIG_H_ */
