/*
 * events.h
 *
 *  Created on: Nov 9, 2022
 *      Author: janoko
 */

#ifndef QUECTEL_EC25_EVENTS_H
#define QUECTEL_EC25_EVENTS_H

#define QTEL_RTOS_EVT_READY              0x00000100U
#define QTEL_RTOS_EVT_NEW_STATE          0x00000200U
#define QTEL_RTOS_EVT_ACTIVED            0x00000400U
#define QTEL_RTOS_EVT_RESP_CONNECT       0x00000800U
#define QTEL_RTOS_EVT_RESP_CONNECT_CLOSE 0x00001000U
//socket
#define QTEL_RTOS_EVT_GPS_NEW_STATE      0x00002000U
// net
#define QTEL_RTOS_EVT_NET_NEW_STATE      0x00004000U
//socket
#define QTEL_RTOS_EVT_SOCKCLIENT_NEW_EVT 0x00010000U
// ntp
#define QTEL_RTOS_EVT_NTP_SYNCED         0x00020000U
// ntp
#define QTEL_RTOS_EVT_HTTP_NEW_STATE     0x00040000U

#define QTEL_RTOS_EVT_ALL QTEL_RTOS_EVT_READY | QTEL_RTOS_EVT_NEW_STATE | QTEL_RTOS_EVT_ACTIVED |\
                          QTEL_RTOS_EVT_GPS_NEW_STATE | QTEL_RTOS_EVT_NET_NEW_STATE |\
                          QTEL_RTOS_EVT_SOCKCLIENT_NEW_EVT |\
                          QTEL_RTOS_EVT_NTP_SYNCED



#endif /* QUECTEL_EC25_EVENTS_H */
